name: KillRewards
main: com.gmail.falistos.KillRewards.Main
version: 1.0.4
depend: [Vault]
commands:
  killrewards:
    description: Manage KillRewards.
permissions:
  killrewards.earn:
    description: Allow to earn money.
    default: true
  killrewards.reload:
    description: Allow to reload plugin.
    default: op